Mark/homepage
mgkram4/gdsc pull request #15
Opened 2024-01-25 19:46 UTC by mgkram4

Added New home page. Reworked and added nav hamburger. Added bottom nav for mobile users.

**PR checklist (requester)**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Your code is documented

**PR checklist (reviewer)**

// TODO

**Other information**:

2024-01-26 04:16 UTC, yzerr0 reviewed
lgtm!

2024-01-26 04:43 UTC, blbergo commented on src/app/homepage/postsmall.tsx
`post-small.tsx`

2024-01-26 04:44 UTC, blbergo commented on src/app/homepage/postsmall.tsx
> +  const { data, error } = await supabase.from("recipes").select("*, users(*)");
do you need every field from users?

2024-01-26 04:44 UTC, blbergo commented on src/app/homepage/postsmall.tsx
> +                "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi eos, earum mollitia tenetur fuga veniam voluptatum quo, dolorem ipsam"}
replace with empty string

2024-01-26 04:45 UTC, blbergo commented on src/app/homepage/postsmall.tsx
> +                <img
lets add it now instead of later

2024-01-26 04:46 UTC, blbergo commented on src/app/homepage/postsmall.tsx
> +                  Profile Picture: {recipe.users?.profilePicture}
how is this stored in the db? Is it as an html img tag, a url, etc

2024-01-26 04:47 UTC, blbergo commented on src/app/homepage/postsmall.tsx
> +                  {new Date(recipe.date_published).toDateString()}
dates in supabase are stored in UTC time, does .toDateString() return in utc format, or the user's local format?

2024-01-26 04:48 UTC, blbergo commented on src/app/homepage/swipecarousel.tsx
`swipe-carousel.tsx`

2024-01-26 04:49 UTC, blbergo commented on src/app/homepage/sidebar.tsx
We will need to fill this in with actual data, but that's probably best for another PR

2024-01-26 04:50 UTC, blbergo commented on src/app/homepage/timeline.tsx
> +  const { data, error } = await supabase.from("recipes").select();
later I will go in and replace this with the supabase edge function for getting recommended recipes

2024-01-26 04:51 UTC, blbergo commented on src/app/homepage/timeline.tsx
> +  const { data, error } = await supabase.from("recipes").select();
in general though, we want to avoid making select * statements, because they are very expensive, especially with React rendering, which may call `select()` multiple times per render.

2024-01-26 04:52 UTC, blbergo commented on src/app/page.tsx
> +      <Sidebar />
can we add sidebar to the layout instead?

2024-01-26 04:53 UTC, blbergo commented on src/app/page.tsx
> +      <Timeline />
I  like what you are doing here, but I think this is a broad, especially since `/app/homepage/timeline` creates a route that serves the exact same component

2024-01-26 04:53 UTC, blbergo commented on src/components/bottomnavbar.tsx
> +export default function bottomnavbar() {
BottomoNavbar

2024-01-26 04:54 UTC, blbergo commented on src/components/bottomnavbar.tsx
`bottom-navbar.tsx`

2024-01-26 04:54 UTC, blbergo commented on src/components/button/navhamburger.tsx
> +export default function navhamburger() {
same here, NavHamburger

2024-01-26 04:54 UTC, blbergo commented on src/components/button/navhamburger.tsx
and here

2024-01-26 04:55 UTC, blbergo commented on src/components/button/navhamburger.tsx
> +  const handleLinkClick = () => {
you can type this to be an event handler as well, so you don't have to use the arrow function in the onClick() part of the element

2024-01-26 04:56 UTC, blbergo commented on src/components/button/navhamburger.tsx
> +          <span className="">Shopping List</span>
are these empty classnames necessary?

2024-01-26 04:56 UTC, blbergo commented on src/components/navbar.tsx
I actually wrote a navbar in my PR that switches automatically depending on the route :)

2024-01-26 04:57 UTC, blbergo commented on src/config/routes.ts
> +  PROFILE = "",
where are the routes for these?

2024-01-26 04:57 UTC, blbergo commented on tsconfig.json
> +    "target": "es2017",
why did we change to es17?

2024-01-26 04:58 UTC, blbergo requested changes
overall looks ok, take a look over my comments before addressing

2024-01-26 22:59 UTC, mgkram4 commented on src/app/page.tsx
> +      <Sidebar />
I ended up putting sidebar in the timeline coudnt get it in layout just right

2024-01-26 23:01 UTC, mgkram4 commented on src/app/homepage/postsmall.tsx
> +                  {new Date(recipe.date_published).toDateString()}
i swapped to diffefernt local , to date not specific

2024-01-26 23:01 UTC, mgkram4 commented on src/app/homepage/postsmall.tsx
> +                <img
changed it , but coudlnt get to work with carosuel , so just img tag as if of now

2024-01-28 22:28 UTC, blbergo approved these changes

2024-01-28 22:28 UTC, merged