Mark/bookmark page (WIP)
mgkram4/gdsc pull request #19
Opened 2024-02-05 04:12 UTC by mgkram4

Bugs are still persistent, work in progress 
<img width="919" alt="Screenshot 2024-02-04 at 8 11 48 PM" src="https://github.com/mgkram4/gdsc/assets/112028232/2e7c45e9-3375-4419-884e-aff78cfe6851">

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Your code is documented

**PR checklist (reviewer)**

// TODO

**Other information**:

2024-02-06 22:20 UTC, thatfoogabriel commented on src/app/bookmarks/page.tsx
> +      "id, title, short_description, headliner_image, date_published, created_at, updated_at, taste_profile_id, ingredientsId, commentId, bookmark_count, comment_count, rating_count, instructions, em
.select() by itself should grab everything

2024-02-07 04:52 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +  const user = useAuth(router);
useAuth is async, needs await and to be called in fetchData

2024-02-07 04:53 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +      if (user) {
user is never null, this if statement effectively doesn't do anything

2024-02-07 04:54 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +  useEffect(() => {
user can change in many ways in its current form, but we want this to run only once per page. remove it from the dependency array and it will only run once per page load.

2024-02-07 04:54 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +          { onConflict: ["user_id"], ignoreDuplicates: true },
what is this line for?

2024-02-07 04:55 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +  const [isBookmarked, setIsBookmarked] = useState(false);
checkout react's `useToggle`

2024-02-07 04:56 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +import { createClient } from "@utils/supabase/server";
does this have to be a server component?

2024-02-07 04:56 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +  const user = useAuth(router);
needs an await

2024-02-07 04:56 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +  if (!user) {
same thing here, this doesn't do anything

2024-02-07 04:57 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +    .eq("email", user)
use UUID instead, more secure

2024-02-07 04:57 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +    .eq("email", user)
`user` also does not return the email, just an object

2024-02-07 05:01 UTC, blbergo commented on src/app/homepage/post-small.tsx
> +      "id,title, short_description, headliner_image, date_published, rating_count, users(profilePicture),bookmark_count,comment_count",
same thing gabe said for here.

2024-02-07 05:03 UTC, blbergo requested changes
overall looks good, but please checkout my comments regarding useAuth

2024-02-09 21:25 UTC, mgkram4 commented on src/app/bookmarks/bookmark-button.tsx
> +  const [isBookmarked, setIsBookmarked] = useState(false);
I downloaded the NPM for it and tried it out couldn't get it to work quite the way I was trying too

2024-02-10 18:52 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +interface RecipeData {
why not use the types generated by supabase instead?

2024-02-10 18:53 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +        setIsBookmarked(false);
is that not covered when you initialize it to false?

2024-02-10 18:53 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +  }, [userId, recipeId]);
what happens if a user logs out?

2024-02-10 18:54 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +  const [bookmarkCount, setBookmarkCount] = useState<number>(0);
checkout `useToggle()`

2024-02-10 18:55 UTC, blbergo commented on src/app/bookmarks/bookmark-button.tsx
> +      const newBookmarkCount = isBookmarked
what happens if a user spams this button?

2024-02-10 18:56 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +        const { data, error } = await createClient()
await createClient?

2024-02-10 18:56 UTC, blbergo commented on src/app/bookmarks/page.tsx
> +  }, [router]);
what happens if the page changes?

2024-02-10 18:58 UTC, blbergo approved these changes
overall looks good, much better coding style. Address my comments that aren't questions and you are good to merge.

2024-02-11 06:21 UTC, merged